version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  flask:
    build: .
    command: python run.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
